import os
import numpy as nmp

# Read .gro file
def read_gro(name):
  inp = open(name,'r')
  L = inp.readline()
  L = inp.readline()
  L = L.split()
  ns = int(L[0])
  
  x = nmp.zeros((ns,3),'d')
  v = nmp.zeros((ns,3),'d')
  RESID = nmp.zeros(ns,'i')
  RESNAME = nmp.zeros((ns,7),'c')
  TYPE = nmp.zeros((ns,5),'c')
  index = nmp.zeros(ns,'i')
  box = nmp.zeros((3,3),'d')
  
  
  print "Read",ns,"sites"

  for i in range(0,ns):
    L = inp.readline()
    RESID[i] = int(L[0:5].split()[0])
    RESNAME[i] = L[5:10]
    TYPE[i] = L[10:15]
    index[i] = int(L[15:20].split()[0])
    
    L2 = L[20:].split()
    
    x[i,0] = float(L2[0])
    x[i,1] = float(L2[1])
    x[i,2] = float(L2[2])
    
    # Store velocities if they exist
    #if (L2[3]):
    #  v[i,0] = float(L2[3])
    #  v[i,1] = float(L2[4])
    #  v[i,2] = float(L2[5])

  L = inp.readline()
  L = L.split()
  box[0,0] = float(L[0])
  box[1,1] = float(L[1])
  box[2,2] = float(L[2])

  if (len(L)>3):
    box[1,0] = float(L[3])  
    box[2,0] = float(L[4])  
    box[0,1] = float(L[5])  
    
    box[2,1] = float(L[6])  
    box[0,2] = float(L[7])  
    box[1,2] = float(L[8])  
  
  inp.close()
  
  # Package everything into a list
  RT = [ns, x, v, RESID, RESNAME, TYPE, index, box]
  print "Return contains [ns, X, V, RESID, RESNAME, TYPE, index, box]"
  return RT

def write_gro(name, x, RID, RNM, TP, indx, bx):
  ns = nmp.shape(x)[0]
  otp = open(name,'w')

  otp.write('Generated by some stpuid python code\n')

  line = '%d\n' % ns
  otp.write(line)

  for i in range(0,ns):
    nm = ''.join(RNM[i])
    tp = ''.join(TP[i])
    nm = nm.lstrip().rstrip()
    tp = tp.lstrip().rstrip()
    line = '%5d%5s%5s%5d%8.3f%8.3f%8.3f\n' % (RID[i], nm, tp, indx[i] % 99999, x[i][0], x[i][1], x[i][2])
    otp.write(line)

  line = '%f %f %f\n' % (bx[0,0], bx[1,1], bx[2,2])
  otp.write(line)

  otp.close()
  
def write_gro_vel(name, x, v, RID, RNM, TP, indx, bx):
  ns = nmp.shape(x)[0]
  otp = open(name,'w')

  otp.write('Generated by some stpuid python code\n')

  line = '%d\n' % ns
  otp.write(line)

  for i in range(0,ns):
    nm = ''.join(RNM[i])
    tp = ''.join(TP[i])
    nm = nm.lstrip().rstrip()
    tp = tp.lstrip().rstrip()
    line = '%5d%5s%5s%5d%8.3f%8.3f%8.3f%8.4f%8.4f%8.4f\n' % (RID[i], nm, tp, indx[i], x[i][0], x[i][1], x[i][2], v[i][0], v[i][1], v[i][2] )
    otp.write(line)

  line = '%f %f %f\n' % (bx[0,0], bx[1,1], bx[2,2])
  otp.write(line)

  otp.close()
  

