import numpy as nmp
import pbc_utils as pbc
import sys
import os
import random as rand

def write_lammps_dynamic2(x, box, npar, nch, chl, frac, n_ci, name):
  ns = nmp.shape(x)[0]

  if (ns != (n_ci*3 + nch*chl)):
    print('Error in the number of sites!')
    return

  otp = open(name,'w')


  otp.write('Generated by RARs stupid code\n\n')

  line = '%d atoms\n' % (nch*chl + 3*n_ci )
  otp.write(line)

  line = '%d bonds\n' % (nch*(chl-1) + 2*n_ci )
  otp.write(line)

  otp.write('2 atom types\n2 bond types\n')

  boxh = 0.5*box
  line = '%f   %f xlo xhi\n' % (-boxh[0], boxh[0])
  otp.write(line)
  line = '%f   %f ylo yhi\n' % (-boxh[1], boxh[1])
  otp.write(line)
  line = '%f   %f zlo zhi\n' % (-boxh[2], boxh[2])
  otp.write(line)

  otp.write('\nMasses\n\n')
  otp.write('1  1.000000\n')
  otp.write('2  1.000000\n')
  otp.write('\nAtoms\n\n')
  

  for i in range(0,ns):
    x[i] = pbc.pbc_inbox(x[i],box,boxh)
  
  i1 = 1
  # Write the polymer positions
  previous_sticky = 0;
  for i in range(0,nch):
    for j in range(0,chl):
      if ( rand.random() < frac and previous_sticky == 0 ):
        line = '%d %d %d     %f  %f  %f\n' % (i1,ns+1, 2, x[i1-1,0], x[i1-1,1], x[i1-1,2])
        previous_sticky = 1
      else:
        line = '%d %d %d     %f  %f  %f\n' % (i1,i1,1, x[i1-1,0], x[i1-1,1], x[i1-1,2])
        #line = '%d %d %d     %f  %f  %f\n' % (i1,i+1,1, x[i1-1,0], x[i1-1,1], x[i1-1,2])
        previous_sticky = 0
      otp.write(line)
      i1 += 1

  # Write the CI positions
  for i in range(0,n_ci):
    for j in range(0,3):
      if ( j == 1 ):
        line = '%d %d %d     %f  %f  %f\n' % (i1,ns+1,2, x[i1-1,0], x[i1-1,1], x[i1-1,2])
      else:
        line = '%d %d %d     %f  %f  %f\n' % (i1,i1,1, x[i1-1,0], x[i1-1,1], x[i1-1,2])
      otp.write(line)
      i1 += 1


  line = '\nBonds\n\n'
  otp.write(line)
  bi = 1

  # Write the polymer bonds
  for i in range(0,nch):
    for j in range(0,chl-1):
      i1 = chl*i + j + 1
      i2 = i1 + 1
      line = '%d  %d  %d  %d\n' % (bi, 1, i1, i2)
      otp.write(line)
      bi += 1

  # Write the CI bonds
  for i in range(0,n_ci):
    for j in range(0,2):
      i1 = chl*nch + 3*i + j + 1
      i2 = i1 + 1
      line = '%d  %d  %d  %d\n' % (bi, 1, i1, i2)
      otp.write(line)
      bi += 1

  print("**************************************")
  print("* NOTE: Swapping molecule id =", ns+1)
  print("**************************************")


  otp.close()


def write_lammps_dynamic(x, box, npar, nch, chl, freq, ci_flag, name):
  ns = nmp.shape(x)[0]

  if (ns != (n_ci*3 + nch*chl)):
    print('Error in the number of sites!')
    return

  otp = open(name,'w')


  otp.write('Generated by RARs stupid code\n\n')

  line = '%d atoms\n' % (nch*chl + npar*50)
  otp.write(line)

  line = '%d bonds\n' % (nch*(chl-1) + 49*npar)
  otp.write(line)
  otp.write('0 angles\n')
  otp.write('0 dihedrals\n')
  otp.write('0 impropers\n\n')

  if (npar > 0):
    otp.write('3 atom types\n2 bond types\n')
  else:
    otp.write('2 atom types\n1 bond types\n')
  otp.write('0 angle types\n')
  otp.write('0 dihedral types\n')
  otp.write('0 improper types\n\n')

  boxh = 0.5*box
  line = '%f   %f xlo xhi\n' % (-boxh[0], boxh[0])
  otp.write(line)
  line = '%f   %f ylo yhi\n' % (-boxh[1], boxh[1])
  otp.write(line)
  line = '%f   %f zlo zhi\n' % (-boxh[2], boxh[2])
  otp.write(line)

  otp.write('\nMasses\n\n')
  otp.write('1  1.000000\n')
  otp.write('2  1.000000\n')
  if (npar > 0):
    otp.write('2 1.000000\n')
    otp.write('3 1.000000\n')
  otp.write('\nAtoms\n\n')
  

  for i in range(0,ns):
    x[i] = pbc.pbc_inbox(x[i],box,boxh)
  
  i1 = 1
  # Write the polymer positions
  for i in range(0,nch):
    for j in range(0,chl):
      if ( i1%freq == 0 ):
        line = '%d %d %d     %f  %f  %f\n' % (i1,nch+1,2, x[i1-1,0], x[i1-1,1], x[i1-1,2])
      else:
        line = '%d %d %d     %f  %f  %f\n' % (i1,i+1,1, x[i1-1,0], x[i1-1,1], x[i1-1,2])
      otp.write(line)
      i1 += 1

  # Write the particle positions
  for i in range(nch, nch+npar):
    line = '%d %d %d     %f  %f  %f\n' % (i1,i+1,3, x[i1-1,0], x[i1-1,1], x[i1-1,2])
    otp.write(line)
    i1 += 1
    for j in range(1,50):
      line = '%d %d %d     %f  %f  %f\n' % (i1,i+1,2, x[i1-1,0], x[i1-1,1], x[i1-1,2])
      otp.write(line)
      i1 += 1

  line = '\nBonds\n\n'
  otp.write(line)
  bi = 1

  # Write the polymer bonds
  for i in range(0,nch):
    for j in range(0,chl-1):
      i1 = chl*i + j + 1
      i2 = i1 + 1
      line = '%d  %d  %d  %d\n' % (bi, 1, i1, i2)
      otp.write(line)
      bi += 1
  # Write the particle bonds
  for i in range(0,npar):
    i1 = nch*chl + i*50 + 1
    for j in range(1,50):
      i2 = i1 + j
      line = '%d  %d  %d  %d\n' % (bi, 2, i1, i2)
      otp.write(line)
      bi += 1

  otp.close()


def write_lammps(x, box, npar, nch, chl, name):
  ns = nmp.shape(x)[0]

  if (ns != (npar*50 + nch*chl)):
    print('Error in the number of sites!')
    return

  otp = open(name,'w')


  otp.write('Generated by RARs stupid code\n\n')

  line = '%d atoms\n' % (nch*chl + npar*50)
  otp.write(line)

  line = '%d bonds\n' % (nch*(chl-1) + 49*npar)
  otp.write(line)
  otp.write('0 angles\n')
  otp.write('0 dihedrals\n')
  otp.write('0 impropers\n\n')

  if (npar > 0):
    otp.write('3 atom types\n2 bond types\n')
  else:
    otp.write('1 atom types\n1 bond types\n')
  otp.write('0 angle types\n')
  otp.write('0 dihedral types\n')
  otp.write('0 improper types\n\n')

  boxh = 0.5*box
  line = '%f   %f xlo xhi\n' % (-boxh[0], boxh[0])
  otp.write(line)
  line = '%f   %f ylo yhi\n' % (-boxh[1], boxh[1])
  otp.write(line)
  line = '%f   %f zlo zhi\n' % (-boxh[2], boxh[2])
  otp.write(line)

  otp.write('\nMasses\n\n')
  otp.write('1  1.000000\n')
  if (npar > 0):
    otp.write('2 1.000000\n')
    otp.write('3 1.000000\n')
  otp.write('Atoms\n\n')
  

  for i in range(0,ns):
    x[i] = pbc.pbc_inbox(x[i],box,boxh)
  
  i1 = 1
  # Write the polymer positions
  for i in range(0,nch):
    for j in range(0,chl):
      line = '%d %d %d     %f  %f  %f\n' % (i1,i+1,1, x[i1-1,0], x[i1-1,1], x[i1-1,2])
      otp.write(line)
      i1 += 1

  # Write the particle positions
  for i in range(nch, nch+npar):
    line = '%d %d %d     %f  %f  %f\n' % (i1,i+1,3, x[i1-1,0], x[i1-1,1], x[i1-1,2])
    otp.write(line)
    i1 += 1
    for j in range(1,50):
      line = '%d %d %d     %f  %f  %f\n' % (i1,i+1,2, x[i1-1,0], x[i1-1,1], x[i1-1,2])
      otp.write(line)
      i1 += 1

  line = '\nBonds\n\n'
  otp.write(line)
  bi = 1

  # Write the polymer bonds
  for i in range(0,nch):
    for j in range(0,chl-1):
      i1 = chl*i + j + 1
      i2 = i1 + 1
      line = '%d  %d  %d  %d\n' % (bi, 1, i1, i2)
      otp.write(line)
      bi += 1
  # Write the particle bonds
  for i in range(0,npar):
    i1 = nch*chl + i*50 + 1
    for j in range(1,50):
      i2 = i1 + j
      line = '%d  %d  %d  %d\n' % (bi, 2, i1, i2)
      otp.write(line)
      bi += 1

  otp.close()

